stages:
  - prebuild
  - build

build:project:
  stage: prebuild
  image: node:16
  tags:
    - docker
  script:
    - npm install
    - npm run build
  only:
    - tags
  except:
    - branches
  artifacts:
    paths:
      - dist
      - package-lock.json
      - node_modules
    expire_in: 1 days


build:docker:x64:
  stage: build
  before_script:
    - echo ${CI_REGISTRY_PASSWORD} | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  after_script:
    - docker logout $CI_REGISTRY
  needs:
    - 'build:project'
  tags:
    - shell
  only:
    - tags
  except:
    - branches
  script:
    - |
      if [[ -z "$CI_COMMIT_TAG" ]]; then
        export CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG}
        export CI_APPLICATION_TAG=${CI_APPLICATION_TAG:-$CI_COMMIT_SHA}
      else
        export CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$CI_REGISTRY_IMAGE}
        export CI_APPLICATION_TAG=${CI_APPLICATION_TAG:-$CI_COMMIT_TAG}
      fi
    - docker build  --target x64 -t $CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG .
    - docker push  $CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG

build:docker:arm64:
  stage: build
  before_script:
    - echo ${CI_REGISTRY_PASSWORD} | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  after_script:
    - docker logout $CI_REGISTRY
  needs:
    - 'build:project'
  tags:
    - shell
  only:
    - tags
  except:
    - branches
  script:
    - |
      if [[ -z "$CI_COMMIT_TAG" ]]; then
        export CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG}
        export CI_APPLICATION_TAG=${CI_APPLICATION_TAG:-$CI_COMMIT_SHA}
      else
        export CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$CI_REGISTRY_IMAGE}
        export CI_APPLICATION_TAG=${CI_APPLICATION_TAG:-$CI_COMMIT_TAG}
      fi
    - docker buildx  --target aarch64 --p -t $CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG  --platform linux/arm64 .
    - docker push  $CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG
